
<div data-bind="scope: 'success-page-section'" id="success-page-section">
   <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
   {
       "*": {
           "Magento_Ui/js/core/app": {
               "components": {
                   "success-page-section": {
                       "component": "AtPay_CustomPayment/js/success-page"
                   }
               }
           }
       }
   }
</script>